script:
  - npm test
#  - node_modules/.bin/protractor e2e/conf.js --browser=firefox
language: node_js
node_js:
  - "0.10"
before_script:
  - npm i -g bower
  - npm i
  - bower install
  - "export DISPLAY=:99.0"
  - npm start &
  - sleep 5
