script:
  - npm test --single-run
#  - node_modules/.bin/protractor e2e/conf.js --browser=firefox
language: node_js
node_js:
  - "0.10"
before_script:
  - npm i -g bower
  - npm i
  - "export DISPLAY=:99.0"
