script:
#  - npm test
  - protractor test/e2e/conf.js --browser=firefox
language: node_js
node_js:
  - "0.10"
before_script:
  - npm i -g bower
  - npm i
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm start &
  - sleep 5
  - webdriver-manager update --standalone --firefox
  - webdriver-manager start -passthru &
  - sleep 5
